// <auto-generated/>
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;
using Arc.Collections;
using Arc.Threading;
using Tinyhand;
using Tinyhand.IO;
using Tinyhand.Resolvers;
using ValueLink;
using ValueLink.Integrality;

#nullable enable
#pragma warning disable CS0169
#pragma warning disable CS1591

namespace ValueLink.Generator
{
    static class Generated
    {
        internal static void __gen__cl()
        {
            GeneratedResolver.Instance.SetFormatter(new Tinyhand.Formatters.TinyhandObjectFormatter<Sandbox.JournalData.GoshujinClass>());
            GeneratedResolver.Instance.SetFormatterGenerator(Type.GetType("Sandbox.CrystalSupplement+Data+PlaneItem+GoshujinClass")!, static (x, y) =>
            {
                var formatter = Activator.CreateInstance(typeof(Tinyhand.Formatters.TinyhandObjectFormatter<>).MakeGenericType(x));
                return (ITinyhandFormatter)formatter!;
            });
            GeneratedResolver.Instance.SetFormatter(new Tinyhand.Formatters.TinyhandObjectFormatter<Sandbox.SpSecondClass.GoshujinClass>());
            GeneratedResolver.Instance.SetFormatter(new Tinyhand.Formatters.TinyhandObjectFormatter<Sandbox.SpClassPoint.GoshujinClass>());
        }
    }
}

namespace ValueLink
{
    public static class ValueLinkModule_Playground
    {
        private static bool Initialized;

        [ModuleInitializer]
        public static void Initialize()
        {
            if (Initialized) return;
            Initialized = true;

            ValueLink.Generator.Generated.__gen__cl();
        }
    }
}
